services:

  mysql:
    image: mysql:8.4

    container_name: jobtracker-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: vatsalsolanki19/jobtracker-backend:latest

    container_name: jobtracker-backend

    ports:
      - "8081:8081"

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

    depends_on:
      - mysql

  frontend:
    image: vatsalsolanki19/jobtracker-frontend:latest

    container_name: jobtracker-frontend

    ports:
      - "3000:3000"

    environment:
      VITE_API_URL: ${VITE_API_URL}

    depends_on:
      - backend

volumes:
  mysql_data: