apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vatsalsolanki19/jobtracker-backend:latest
          env:
            - name: DB_USER
              value: jobtracker 
            - name: DB_PASSWORD
              value: jobtracker123
            - name: DB_HOST
              value: mysql 
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: jobtracker
          ports:
            - containerPort: 8081
              name: backend
